// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOa0xzsObm9cjeFdcJni17bojnhH2avqc',
    appId: '1:1044956378515:web:f5dcabb336d8c36f842466',
    messagingSenderId: '1044956378515',
    projectId: 'grip-d2cbc',
    authDomain: 'grip-d2cbc.firebaseapp.com',
    storageBucket: 'grip-d2cbc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwo-z667ouqnRX9JNx0_xUCRvnJDGvOFc',
    appId: '1:1044956378515:android:16745ad3cf4c73b6842466',
    messagingSenderId: '1044956378515',
    projectId: 'grip-d2cbc',
    storageBucket: 'grip-d2cbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDruZY3v36nPD410_Av8dF6CoFljWBS5cU',
    appId: '1:1044956378515:ios:b110c2cc9fdcd038842466',
    messagingSenderId: '1044956378515',
    projectId: 'grip-d2cbc',
    storageBucket: 'grip-d2cbc.appspot.com',
    iosClientId: '1044956378515-sm8qmui7ufou8eie4ski0uu842e0pkkf.apps.googleusercontent.com',
    iosBundleId: 'com.arjun.grip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDruZY3v36nPD410_Av8dF6CoFljWBS5cU',
    appId: '1:1044956378515:ios:cf8f4a91b44a5870842466',
    messagingSenderId: '1044956378515',
    projectId: 'grip-d2cbc',
    storageBucket: 'grip-d2cbc.appspot.com',
    iosClientId: '1044956378515-uoen3up006c7j3rsm69jnbe1gijl7iak.apps.googleusercontent.com',
    iosBundleId: 'com.example.grip',
  );
}
